import type { Metadata } from "next";
import { Sen } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const josef = Sen(
  {
    subsets:['latin'],
    weight:['400','500','600','700'],
    display:'swap'
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={josef.className}>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
