import type { Metadata } from "next";
// import { Sen } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ChatWidget from "@/components/ChatWidget";

// const josef = Sen(
//   {
//     subsets:['latin'],
//     weight:['400','500','600','700'],
//     display:'swap'
//   }
// );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // className={josef.className}
  return (
    <html lang="en">
      <body >
        <Navbar />
        {children}
        <ChatWidget/>
        <Footer/>
      </body>
    </html>
  );
}
